# Triton Config
triton:
  server_ip: "192.168.1.80"
  server_port: 8000

# MQTT Config
mqtt:
 enabled: "False"
 broker_dns: "10.152.183.204"
 broker_port: 1883
 user: "mqtt-user-01"

# Redis Config
redis:
 enabled: "False"
 host: "192.168.1.XXX"
 port: 6379

# Camera feed locations
locations:
  - code: loc-sea1
    city: "Bellevue"
    state: "Washington"
    feeds:
      - "rtsp://<url>:1935/live/CCTV001.stream"
      - "rtsp://<url>:1935/live/CCTV002.stream"
      - "rtsp://<url>:1935/live/CCTV003.stream"
      - "rtsp://<url>:1935/live/CCTV004.stream"
      - "rtsp://<url>:1935/live/CCTV005.stream"
      - "rtsp://<url>:1935/live/CCTV006.stream"
      - "rtsp://<url>:1935/live/CCTV007.stream"
      - "rtsp://<url>:1935/live/CCTV008.stream"
      - "rtsp://<url>:1935/live/CCTV026.stream"
      - "rtsp://<url>:1935/live/CCTV028.stream"
